export enum ETasksQueryKeys {
  SET_TASKS_DATA = "SET_TASKS_DATA",
  SET_TASKS_DATA_ITEM = "SET_TASKS_DATA_ITEM",
  CREATE_TASK_ITEM = "CREATE_TASK_ITEM",
  DELETE_TASK_ITEM = "DELETE_TASK_ITEM",
  UPDATE_TASK_ITEM = "UPDATE_TASK_ITEM",
}
